import 'package:uuid/uuid.dart';

class AvailableTimeZone {
  final String id;
  final String identifier;
  final String cityName;
  final String abbreviation;

  AvailableTimeZone({
    required this.identifier,
    required this.cityName,
    required this.abbreviation,
  }) : id = Uuid().v4();

  static List<AvailableTimeZone> get all => [
        // AFRICA
        AvailableTimeZone(identifier: "Africa/Cairo", cityName: "Cairo", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Africa/Algiers", cityName: "Algiers", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Africa/Tunis", cityName: "Tunis", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Africa/Khartoum", cityName: "Khartoum", abbreviation: "CAT"),
        AvailableTimeZone(identifier: "Africa/Johannesburg", cityName: "Johannesburg", abbreviation: "SAST"),
        AvailableTimeZone(identifier: "Africa/Lagos", cityName: "Lagos", abbreviation: "WAT"),
        AvailableTimeZone(identifier: "Africa/Nairobi", cityName: "Nairobi", abbreviation: "EAT"),
        AvailableTimeZone(identifier: "Africa/Casablanca", cityName: "Casablanca", abbreviation: "WET"),
        AvailableTimeZone(identifier: "Africa/Accra", cityName: "Accra", abbreviation: "GMT"),
        AvailableTimeZone(identifier: "Africa/Bamako", cityName: "Bamako", abbreviation: "GMT"),
        AvailableTimeZone(identifier: "Africa/Luanda", cityName: "Luanda", abbreviation: "WAT"),
        AvailableTimeZone(identifier: "Africa/Maputo", cityName: "Maputo", abbreviation: "CAT"),
        AvailableTimeZone(identifier: "Africa/Gaborone", cityName: "Gaborone", abbreviation: "CAT"),
        AvailableTimeZone(identifier: "Africa/Kampala", cityName: "Kampala", abbreviation: "EAT"),
        AvailableTimeZone(identifier: "Africa/Dakar", cityName: "Dakar", abbreviation: "GMT"),
        AvailableTimeZone(identifier: "Africa/Harare", cityName: "Harare", abbreviation: "CAT"),
        AvailableTimeZone(identifier: "Africa/Windhoek", cityName: "Windhoek", abbreviation: "CAT"),

        // SOUTH AMERICA
        AvailableTimeZone(identifier: "America/Sao_Paulo", cityName: "Sao Paulo", abbreviation: "BRT"),
        AvailableTimeZone(identifier: "America/Argentina/Buenos_Aires", cityName: "Buenos Aires", abbreviation: "ART"),
        AvailableTimeZone(identifier: "America/Santiago", cityName: "Santiago", abbreviation: "CLT"),
        AvailableTimeZone(identifier: "America/Lima", cityName: "Lima", abbreviation: "PET"),
        AvailableTimeZone(identifier: "America/Bogota", cityName: "Bogota", abbreviation: "COT"),
        AvailableTimeZone(identifier: "America/Caracas", cityName: "Caracas", abbreviation: "VET"),
        AvailableTimeZone(identifier: "America/Montevideo", cityName: "Montevideo", abbreviation: "UYT"),
        AvailableTimeZone(identifier: "America/La_Paz", cityName: "La Paz", abbreviation: "BOT"),
        AvailableTimeZone(identifier: "America/Asuncion", cityName: "Asuncion", abbreviation: "PYT"),
        AvailableTimeZone(identifier: "America/Guyana", cityName: "Guyana", abbreviation: "GYT"),
        AvailableTimeZone(identifier: "America/Cayenne", cityName: "Cayenne", abbreviation: "GFT"),

        // CENTRAL AMERICA / CARIBBEAN
        AvailableTimeZone(identifier: "America/Mexico_City", cityName: "Mexico City", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Panama", cityName: "Panama", abbreviation: "EST"),
        AvailableTimeZone(identifier: "America/Costa_Rica", cityName: "Costa Rica", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Havana", cityName: "Havana", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Santo_Domingo", cityName: "Santo Domingo", abbreviation: "AST"),
        AvailableTimeZone(identifier: "America/Belize", cityName: "Belize", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Guatemala", cityName: "Guatemala", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Managua", cityName: "Managua", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Port_of_Spain", cityName: "Port of Spain", abbreviation: "AST"),
        AvailableTimeZone(identifier: "America/Curacao", cityName: "Curacao", abbreviation: "AST"),

        // NORTH AMERICA
        AvailableTimeZone(identifier: "America/New_York", cityName: "New York", abbreviation: "EST"),
        AvailableTimeZone(identifier: "America/New_York", cityName: "Miami", abbreviation: "EST"),
        AvailableTimeZone(identifier: "America/New_York", cityName: "Boston", abbreviation: "EST"),
        AvailableTimeZone(identifier: "America/Chicago", cityName: "Chicago", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Chicago", cityName: "Houston", abbreviation: "CST"),
        AvailableTimeZone(identifier: "America/Denver", cityName: "Denver", abbreviation: "MST"),
        AvailableTimeZone(identifier: "America/Phoenix", cityName: "Phoenix", abbreviation: "MST"),
        AvailableTimeZone(identifier: "America/Los_Angeles", cityName: "Los Angeles", abbreviation: "PST"),
        AvailableTimeZone(identifier: "America/Los_Angeles", cityName: "San Francisco", abbreviation: "PST"),
        AvailableTimeZone(identifier: "America/Los_Angeles", cityName: "Seattle", abbreviation: "PST"),
        AvailableTimeZone(identifier: "Pacific/Honolulu", cityName: "Honolulu", abbreviation: "HST"),
        AvailableTimeZone(identifier: "America/Toronto", cityName: "Toronto", abbreviation: "EST"),
        AvailableTimeZone(identifier: "America/Vancouver", cityName: "Vancouver", abbreviation: "PST"),
        AvailableTimeZone(identifier: "America/Anchorage", cityName: "Anchorage", abbreviation: "AKST"),
        AvailableTimeZone(identifier: "America/Whitehorse", cityName: "Whitehorse", abbreviation: "MST"),
        AvailableTimeZone(identifier: "America/St_Johns", cityName: "St. John's", abbreviation: "NST"),

        // EUROPE
        AvailableTimeZone(identifier: "Europe/London", cityName: "London", abbreviation: "GMT"),
        AvailableTimeZone(identifier: "Europe/Paris", cityName: "Paris", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Berlin", cityName: "Berlin", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Zurich", cityName: "Zürich", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Madrid", cityName: "Madrid", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Rome", cityName: "Rome", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Amsterdam", cityName: "Amsterdam", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Stockholm", cityName: "Stockholm", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Athens", cityName: "Athens", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Europe/Warsaw", cityName: "Warsaw", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Prague", cityName: "Prague", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Budapest", cityName: "Budapest", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Helsinki", cityName: "Helsinki", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Europe/Dublin", cityName: "Dublin", abbreviation: "IST"),
        AvailableTimeZone(identifier: "Europe/Lisbon", cityName: "Lisbon", abbreviation: "WET"),
        AvailableTimeZone(identifier: "Europe/Moscow", cityName: "Moscow", abbreviation: "MSK"),
        AvailableTimeZone(identifier: "Europe/Istanbul", cityName: "Istanbul", abbreviation: "TRT"),
        AvailableTimeZone(identifier: "Europe/Oslo", cityName: "Oslo", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Copenhagen", cityName: "Copenhagen", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Vienna", cityName: "Vienna", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Brussels", cityName: "Brussels", abbreviation: "CET"),
        AvailableTimeZone(identifier: "Europe/Sofia", cityName: "Sofia", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Europe/Bucharest", cityName: "Bucharest", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Europe/Tallinn", cityName: "Tallinn", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Europe/Riga", cityName: "Riga", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Europe/Vilnius", cityName: "Vilnius", abbreviation: "EET"),

        // ASIA
        AvailableTimeZone(identifier: "Asia/Dubai", cityName: "Dubai", abbreviation: "GST"),
        AvailableTimeZone(identifier: "Asia/Riyadh", cityName: "Riyadh", abbreviation: "AST"),
        AvailableTimeZone(identifier: "Asia/Tehran", cityName: "Tehran", abbreviation: "IRST"),
        AvailableTimeZone(identifier: "Asia/Karachi", cityName: "Karachi", abbreviation: "PKT"),
        AvailableTimeZone(identifier: "Asia/Tashkent", cityName: "Tashkent", abbreviation: "UZT"),
        AvailableTimeZone(identifier: "Asia/Kolkata", cityName: "Mumbai", abbreviation: "IST"),
        AvailableTimeZone(identifier: "Asia/Kolkata", cityName: "Delhi", abbreviation: "IST"),
        AvailableTimeZone(identifier: "Asia/Kolkata", cityName: "Bangalore", abbreviation: "IST"),
        AvailableTimeZone(identifier: "Asia/Kolkata", cityName: "Chennai", abbreviation: "IST"),
        AvailableTimeZone(identifier: "Asia/Colombo", cityName: "Colombo", abbreviation: "IST"),
        AvailableTimeZone(identifier: "Asia/Kathmandu", cityName: "Kathmandu", abbreviation: "NPT"),
        AvailableTimeZone(identifier: "Asia/Bangkok", cityName: "Bangkok", abbreviation: "ICT"),
        AvailableTimeZone(identifier: "Asia/Ho_Chi_Minh", cityName: "Ho Chi Minh City", abbreviation: "ICT"),
        AvailableTimeZone(identifier: "Asia/Jakarta", cityName: "Jakarta", abbreviation: "WIB"),
        AvailableTimeZone(identifier: "Asia/Singapore", cityName: "Singapore", abbreviation: "SGT"),
        AvailableTimeZone(identifier: "Asia/Kuala_Lumpur", cityName: "Kuala Lumpur", abbreviation: "MYT"),
        AvailableTimeZone(identifier: "Asia/Manila", cityName: "Manila", abbreviation: "PHT"),
        AvailableTimeZone(identifier: "Asia/Taipei", cityName: "Taipei", abbreviation: "CST"),
        AvailableTimeZone(identifier: "Asia/Hong_Kong", cityName: "Hong Kong", abbreviation: "HKT"),
        AvailableTimeZone(identifier: "Asia/Shanghai", cityName: "Shanghai", abbreviation: "CST"),
        AvailableTimeZone(identifier: "Asia/Seoul", cityName: "Seoul", abbreviation: "KST"),
        AvailableTimeZone(identifier: "Asia/Tokyo", cityName: "Tokyo", abbreviation: "JST"),
        AvailableTimeZone(identifier: "Asia/Baghdad", cityName: "Baghdad", abbreviation: "AST"),
        AvailableTimeZone(identifier: "Asia/Damascus", cityName: "Damascus", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Asia/Amman", cityName: "Amman", abbreviation: "EET"),
        AvailableTimeZone(identifier: "Asia/Baku", cityName: "Baku", abbreviation: "AZT"),
        AvailableTimeZone(identifier: "Asia/Yerevan", cityName: "Yerevan", abbreviation: "AMT"),
        AvailableTimeZone(identifier: "Asia/Tbilisi", cityName: "Tbilisi", abbreviation: "GET"),
        AvailableTimeZone(identifier: "Asia/Ashgabat", cityName: "Ashgabat", abbreviation: "TMT"),
        AvailableTimeZone(identifier: "Asia/Dushanbe", cityName: "Dushanbe", abbreviation: "TJT"),
        AvailableTimeZone(identifier: "Asia/Phnom_Penh", cityName: "Phnom Penh", abbreviation: "ICT"),
        AvailableTimeZone(identifier: "Asia/Vientiane", cityName: "Vientiane", abbreviation: "ICT"),
        AvailableTimeZone(identifier: "Asia/Pyongyang", cityName: "Pyongyang", abbreviation: "KST"),

        // OCEANIA / PACIFIC
        AvailableTimeZone(identifier: "Australia/Sydney", cityName: "Sydney", abbreviation: "AEST"),
        AvailableTimeZone(identifier: "Australia/Melbourne", cityName: "Melbourne", abbreviation: "AEST"),
        AvailableTimeZone(identifier: "Pacific/Auckland", cityName: "Auckland", abbreviation: "NZST"),
        AvailableTimeZone(identifier: "Pacific/Fiji", cityName: "Fiji", abbreviation: "FJT"),
        AvailableTimeZone(identifier: "Pacific/Guam", cityName: "Guam", abbreviation: "ChST"),
        // Pacific/Tahiti often needs context as Pacific/Tahiti or similar, standard is Pacific/Tahiti
        AvailableTimeZone(identifier: "Pacific/Tahiti", cityName: "Tahiti", abbreviation: "TAHT"),
        // Samoa can be Pacific/Apia
        AvailableTimeZone(identifier: "Pacific/Apia", cityName: "Samoa", abbreviation: "WST"),
        AvailableTimeZone(identifier: "Pacific/Tongatapu", cityName: "Tonga", abbreviation: "TOT"),
        AvailableTimeZone(identifier: "Australia/Adelaide", cityName: "Adelaide", abbreviation: "ACST"),
        AvailableTimeZone(identifier: "Australia/Darwin", cityName: "Darwin", abbreviation: "ACST"),
        AvailableTimeZone(identifier: "Pacific/Chatham", cityName: "Chatham", abbreviation: "CHAST"),
        AvailableTimeZone(identifier: "Pacific/Nauru", cityName: "Nauru", abbreviation: "NRT"),
        AvailableTimeZone(identifier: "Pacific/Niue", cityName: "Niue", abbreviation: "NUT"),
        AvailableTimeZone(identifier: "Pacific/Pago_Pago", cityName: "Pago Pago", abbreviation: "SST"),
        AvailableTimeZone(identifier: "Pacific/Funafuti", cityName: "Funafuti", abbreviation: "TVT"),

        AvailableTimeZone(identifier: "UTC", cityName: "UTC", abbreviation: "UTC"),
  ];
}
